# Generated by Django 5.1.4 on 2026-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_college_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Bhopal', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
