# Generated by Django 6.0.1 on 2026-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_skills_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
